Nome do Jogo: An Undead Heart
FPS: 60
Nível de Resolução do Jogo: 4
Tela Cheia: false
Díretorios:
  Jogos Salvos: Jogos Salvos
  Imagens:
    Menus:
      Principal: Menu Principal
      Opções: Menu de Opções
      Vídeo: Menu de Vídeo
      Novo Jogo: Menu de Novo Jogo
      Carregar Save: Menu para Carregar Jogo Salvo
      Como Jogar: Menu de Como Jogar
Diretórios:
  Pai: Configurações
  Menu das Opções: Menus/Opções
  Controles: Menus/Controles
  Configurações de Vídeo: Menus/Vídeo
  Jogos Salvos: Jogos Salvos
  Menu dos Jogos Salvos: Menus/Jogos Salvos
  Iniciar Novo Jogo: Menus/Inicar Novo Jogo
  Jogo: Jogo
