Diretórios:
  Pai: Configurações
  Menu das Opções: Menus/Opções
  Controles: Menus/Controles
  Configurações de Vídeo: Menus/Vídeo
  Jogos Salvos: Jogos Salvos
  Menu dos Jogos Salvos: Menus/Jogos Salvos
  Iniciar Novo Jogo: Menus/Inicar Novo Jogo
  Jogo: Assets
FPS: '60'
Nível de Resolução do Jogo: 5
Nome do Jogo: LAST SURPRISE
Tela Cheia: false
